project:
  type: book

book:
  title: "Physics Lecture Notes"
  author: "Sai"
  site-url: https://<your-username>.github.io/physics-lecture-notes
  chapters:
    - index.qmd

    - part: "Atomic Physics"
      chapters:
        - notes/atomic/index.qmd
        - notes/atomic/hydrogen.qmd
        


format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    mathjax: true
